"""Official NEXUS qualification assets: manifest, verification, bootstrap.

Two release modes, one rule — never run the purchase gate on unverified assets:
  Mode A (self-contained): everything under assets/ is present and checksummed.
  Mode B (bootstrap): missing files are fetched from the hardcoded trusted URLs
    below and verified against pinned SHA-256 before use. The seller is never
    asked for URLs, files, or choices.
A random user-dropped .pt/.mp4 is NEVER used: only manifest IDs + hashes count.
"""
import hashlib
import os
import urllib.request

QUALIFICATION_VERSION = "1.0"
ASSET_MANIFEST_VERSION = "1.0"

MODEL_URL = "https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt"
COCO8_URL = "https://github.com/ultralytics/assets/releases/download/v0.0.0/coco8.zip"

OFFICIAL_MANIFEST = {
    "qualification_version": QUALIFICATION_VERSION,
    "manifest_version": ASSET_MANIFEST_VERSION,
    "assets": [
        {"asset_id": "nexus-qual-model-yolo11n-v1",
         "name": "NEXUS qualification detection model (reference YOLO11n)",
         "version": "1.0", "type": "model", "filename": "model/yolo11n.pt",
         "size": 5613764,
         "sha256": "0ebbc80d4a7680d14987a577cd21342b65ecfd94632bd9a8da63ae6417644ee1",
         "source": MODEL_URL,
         "purpose": "official NEXUS detection workload"},
        {"asset_id": "nexus-qual-uav-v1",
         "name": "UAV official motion sequence v1 (seeded, 640x480@30, 20 s)",
         "version": "1.0", "type": "video", "filename": "video/uav_test_v1.mp4",
         "size": 9701634,
         "sha256": "5146438f8423aa43b618c07bacc5c9ef3a2cf079962e2133466bf65761b63954",
         "source": "bundled (generated by tools/make_official_assets.py v1.0)",
         "purpose": "official UAV throughput/timing stimulus (NOT drone footage)"},
        {"asset_id": "nexus-qual-rover-v1",
         "name": "Rover official motion sequence v1 (seeded, 640x480@30, 20 s)",
         "version": "1.0", "type": "video", "filename": "video/rover_test_v1.mp4",
         "size": 8337299,
         "sha256": "b9bfe2f5564deb4f83acb211da6159eea14cef54955fc05c3cd9123ec5ae7f38",
         "source": "bundled (generated by tools/make_official_assets.py v1.0)",
         "purpose": "official rover throughput/timing stimulus (NOT field footage)"},
        {"asset_id": "nexus-qual-coco8-v1",
         "name": "Accuracy validation set (COCO8, 4 train + 4 val images + labels)",
         "version": "1.0", "type": "dataset", "filename": "accuracy/coco8.zip",
         "size": 443158,
         "sha256": "54c67fe9ef88313e021ec0e92b73c200167bb0a86633e8df8658d832cca828c9",
         "tree_sha256": "de3b36b93aa87f9770316333d0aaf81dbc50a27dcfe80229c7bda4a5c0d789b6",
         "source": COCO8_URL,
         "purpose": "official labelled accuracy data (real labels, real mAP)"},
    ],
}

class AssetError(RuntimeError):
    pass

def package_root():
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def assets_dir(root=None):
    return os.path.join(root or package_root(), "assets")

def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()

def verify_assets(root=None):
    """Check every official asset. Returns (ok, records). No downloads here."""
    adir = assets_dir(root)
    records = []
    for a in OFFICIAL_MANIFEST["assets"]:
        p = os.path.join(adir, a["filename"])
        rec = {"asset_id": a["asset_id"], "path": p, "expected_sha256": a["sha256"]}
        if not os.path.exists(p):
            rec["status"] = "MISSING"
        elif os.path.getsize(p) != a["size"]:
            rec["status"] = "MISMATCH"
            rec["detail"] = f"size {os.path.getsize(p)} != {a['size']}"
        elif sha256_file(p) != a["sha256"]:
            rec["status"] = "MISMATCH"
            rec["detail"] = "sha256 mismatch — modified or corrupted"
        else:
            rec["status"] = "OK"
        records.append(rec)
    return all(r["status"] == "OK" for r in records), records

def _download(url, dest, progress=None):
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    tmp = dest + ".part"
    try:
        with urllib.request.urlopen(url, timeout=60) as r, open(tmp, "wb") as f:
            total = int(r.headers.get("Content-Length", 0) or 0)
            got = 0
            while True:
                chunk = r.read(1 << 20)
                if not chunk:
                    break
                f.write(chunk)
                got += len(chunk)
                if progress and total:
                    progress(got, total)
    except Exception as e:
        try:
            os.remove(tmp)
        except OSError:
            pass
        raise AssetError(f"download failed for {url}: {e}")
    os.replace(tmp, dest)

def bootstrap(root=None, progress=None):
    """Fetch missing official assets from hardcoded trusted URLs. Verifies each."""
    adir = assets_dir(root)
    _by_id = {a["asset_id"]: a for a in OFFICIAL_MANIFEST["assets"]}
    _, records = verify_assets(root)
    for rec in records:
        if rec["status"] == "OK":
            continue
        a = _by_id[rec["asset_id"]]
        if not a["source"].startswith(("http://", "https://", "file://")):
            raise AssetError(f"{a['asset_id']} is {rec['status']} and has no download "
                             f"source — reinstall the package")
        # Trust comes from the PINNED manifest entry + post-download SHA-256,
        # never from a user-supplied location: sellers cannot set these URLs.
        if progress:
            progress(a["asset_id"], None)
        _download(a["source"], rec["path"])
        if sha256_file(rec["path"]) != a["sha256"]:
            raise AssetError(f"{a['asset_id']} failed checksum after download — "
                             f"mirror untrusted, refusing to qualify")
    ok, records = verify_assets(root)
    if not ok:
        bad = [r for r in records if r["status"] != "OK"]
        raise AssetError(f"assets still unverified after bootstrap: {bad}")
    return records

def _tree_hash(tree_dir):
    h = hashlib.sha256()
    paths = []
    for r, _, fs in os.walk(tree_dir):
        for fn in fs:
            paths.append(os.path.join(r, fn))
    if not paths:
        return None
    for p in sorted(paths):
        h.update(os.path.relpath(p, tree_dir).encode())
        h.update(sha256_file(p).encode())
    return h.hexdigest()

def ensure_accuracy_tree(root=None):
    """The extracted validation tree must exist AND match the pinned tree hash.
    Extracts from the verified ZIP when needed (rigorously verified B)."""
    import zipfile
    adir = assets_dir(root)
    acc = next(a for a in OFFICIAL_MANIFEST["assets"] if a["type"] == "dataset")
    tree = os.path.join(adir, "accuracy", "coco8")
    want = acc.get("tree_sha256")
    if _tree_hash(tree) == want:
        return tree
    zipp = os.path.join(adir, acc["filename"])
    if not (os.path.exists(zipp) and sha256_file(zipp) == acc["sha256"]):
        raise AssetError("accuracy ZIP missing/unverified — cannot build validation set")
    import shutil
    if os.path.isdir(tree):
        shutil.rmtree(tree)
    with zipfile.ZipFile(zipp) as z:
        z.extractall(os.path.join(adir, "accuracy"))
    if _tree_hash(tree) != want:
        raise AssetError("extracted accuracy tree failed hash — refusing to qualify")
    return tree

def ensure_all(root=None, progress=None):
    """Verify; bootstrap if anything is missing; verify again. Raises AssetError
    (benchmark must NOT start) on any failure. Never substitutes user files."""
    ok, records = verify_assets(root)
    if not ok:
        if progress:
            progress("bootstrap", None)
        records = bootstrap(root, progress=progress)
    adir = assets_dir(root)
    vids = [a["filename"] for a in OFFICIAL_MANIFEST["assets"] if a["type"] == "video"]
    uav = next(f for f in vids if "uav" in f)
    rov = next(f for f in vids if "rover" in f)
    mod = next(a["filename"] for a in OFFICIAL_MANIFEST["assets"] if a["type"] == "model")
    acc = next(a for a in OFFICIAL_MANIFEST["assets"] if a["type"] == "dataset")
    paths = {"model": os.path.join(adir, mod),
             "uav_video": os.path.join(adir, uav),
             "rover_video": os.path.join(adir, rov),
             "accuracy_zip": os.path.join(adir, acc["filename"]),
             "accuracy_dir": os.path.join(adir, "accuracy", "coco8"),
             "assets_dir": adir}
    return paths, records
